displayName=FlippingRS
author=jmwri
description=Automatically records your Grand Exchange trades to your flippingrs.com journal
tags=grand exchange,ge,flip,flipping,merching,profit,journal,tracker,tax
plugins=com.flippingrs.FlippingRsPlugin
version=1.0.0
build=standard
